# Your Gemini API key from Google AI Studio
gemini-api-key: "YOUR_GEMINI_API_KEY_HERE"

# Gemini API settings
gemini-settings:
  model: "gemini-1.5-flash"
  temperature: 0.3
  max-tokens: 100
  
# Enable/disable the license validation (set to false since we're using Gemini directly)
license-validation:
  enabled: false

# Machine Learning (ML) module settings
ml-check:
  enabled: true
  frames-to-analyze: 150 # Do not change!
  # Confidence threshold. Recommended 0.80-0.95 to reduce false positives.
  classification-threshold: 0.80

  # How much VL is added for one flag from the anticheat.
  vl-increment: 0.5

  # VL threshold at which the player will be punished.
  violation-threshold: 2

  # Lifetime of one flag in seconds.
  # After this time 1 flag (vl-increment) will completely disappear. (600 = 10 minutes)
  # VL will decrease gradually over this time.
  window: 600

# Alert settings for administration
alerts:
  enabled: true
  permission: "mindai.alerts"
  # Message format. %vl% will now show current VL and threshold (e.g., 6.6/7) instead of the usual 1/1
  message: "&8[&3MindAI&8] &f%player% &bis suspected of cheating &8(&3%probability% | VL: %vl%&8)"

# AUTOMATIC PUNISHMENT (when VL threshold is reached)
auto-punishment:
  # Automatic punishment mode: INSTANT, ANIMATED, ALERTS_ONLY
  # INSTANT is ban without animation, ANIMATED with animation, ALERTS_ONLY just alerts
  mode: INSTANT
  # Command to be executed if INSTANT mode is selected
  command: "ban %player% Your account has been blocked by MindAi system for violating the rules."

# PUNISHMENT ANIMATION (for /mindai punish and ANIMATED mode)
punishment-animation:
  enabled: true
  duration: 5
  levitation-strength: 1
  particle:
    type: REDSTONE
    color: ORANGE
    size: 1.0
    radius: 1.5
    count: 10
  sounds:
    start-sound: ENTITY_EVOKER_PREPARE_SUMMON
    end-sound: ENTITY_WITHER_DEATH
  # Command to be executed AT THE END OF THE ANIMATION
  command: "kick %player% &fYou have been expelled by AI force"