name: MindAI
version: "1.0"
main: ru.Fronzter.MindAc.MindAI
api-version: "1.13"
author: Fronzter
depend: [ProtocolLib]
permissions:
  mindai.alerts:
    description: Allows receiving alerts from the analysis system
    default: op
  mindai.admin:
    description: Allows using administrative commands of the plugin
    default: op

commands:
  mindai:
    description: Main command of the MindAI plugin
    aliases: [mac]
    permission: mindai.admin
    usage: "/<command> [reload|alerts|history]"